### ISSUE TITLE
Quick question about the difference of the test results with MoCo v2

### ISSUE THREAD

**Issue by flrngel** [szq0214/S2-BNN#1]
# Table 4 from S2-BNN Paper
![image](https://user-images.githubusercontent.com/2807595/125279774-4b4a1580-e34f-11eb-8e66-1b0b2611a28e.png)

# Table 3 from MoCo v2
![image](https://user-images.githubusercontent.com/2807595/125279641-248bdf00-e34f-11eb-91b6-bd4f74f28b13.png)

There's a big difference between the two papers, 46.9% (S2-BNN) vs. 60.6% (MoCo v2 - without any methods).
Is there any difference in settings compare to the original paper?

**Comment by szq0214** [comment]
Hi @flrngel, in our paper, the backbone network is an efficient binary neural network instead of the real-valued ResNet-50 (MoCo V2).

**Comment by flrngel** [comment]
gotcha, Thanks!
